2025-01-29 13:16:45,524 INFO    MainThread:11948 [wandb_setup.py:_flush():68] Current SDK version is 0.19.5
2025-01-29 13:16:45,526 INFO    MainThread:11948 [wandb_setup.py:_flush():68] Configure stats pid to 11948
2025-01-29 13:16:45,526 INFO    MainThread:11948 [wandb_setup.py:_flush():68] Loading settings from /home/davindillon/.config/wandb/settings
2025-01-29 13:16:45,527 INFO    MainThread:11948 [wandb_setup.py:_flush():68] Loading settings from /mnt/c/users/davin/OneDrive/Documents/AAA_Ohio_University/Spring25/GameAI/sb3_wandb/cartpole/wandb/settings
2025-01-29 13:16:45,528 INFO    MainThread:11948 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-01-29 13:16:45,529 INFO    MainThread:11948 [wandb_init.py:setup_run_log_directory():637] Logging user logs to /mnt/c/users/davin/OneDrive/Documents/AAA_Ohio_University/Spring25/GameAI/sb3_wandb/cartpole/wandb/run-20250129_131645-n2ujavhn/logs/debug.log
2025-01-29 13:16:45,540 INFO    MainThread:11948 [wandb_init.py:setup_run_log_directory():638] Logging internal logs to /mnt/c/users/davin/OneDrive/Documents/AAA_Ohio_University/Spring25/GameAI/sb3_wandb/cartpole/wandb/run-20250129_131645-n2ujavhn/logs/debug-internal.log
2025-01-29 13:16:45,541 INFO    MainThread:11948 [wandb_init.py:init():756] calling init triggers
2025-01-29 13:16:45,542 INFO    MainThread:11948 [wandb_init.py:init():761] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-01-29 13:16:45,543 INFO    MainThread:11948 [wandb_init.py:init():789] starting backend
2025-01-29 13:16:45,758 INFO    MainThread:11948 [wandb_init.py:init():793] sending inform_init request
2025-01-29 13:16:45,784 INFO    MainThread:11948 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-01-29 13:16:45,785 INFO    MainThread:11948 [wandb_init.py:init():808] backend started and connected
2025-01-29 13:16:45,786 INFO    MainThread:11948 [wandb_init.py:init():901] updated telemetry
2025-01-29 13:16:46,059 INFO    MainThread:11948 [wandb_init.py:init():926] communicating run to backend with 90.0 second timeout
2025-01-29 13:16:46,894 ERROR   MainThread:11948 [wandb_init.py:init():1471] error in wandb.init()
Traceback (most recent call last):
  File "/home/davindillon/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1461, in init
    return wi.init(run_settings, run_config)
  File "/home/davindillon/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 957, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-01-29 13:16:46,992 WARNING MsgRouterThr:11948 [router.py:message_loop():75] message_loop has been closed
